version: '3.8'

services:
  app:
    build: .
    container_name: usermanagement-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
